from django.urls import path

from .views import (
    AppLogoutView,
    CaptchaVerifyView,
    CurrentFactorRouterView,
    ImageVerifyView,
    LoginView,
    OTPResendView,
    OTPVerifyView,
    PasskeyAuthenticationOptionsView,
    PasskeyAuthenticationVerifyView,
    PasskeyRegistrationOptionsView,
    PasskeyRegistrationVerifyView,
    PasskeySetupMFAView,
    PasskeyVerifyView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PasswordResetOTPVerifyView,
    PinSetupView,
    PinVerifyView,
    RegisterView,
    SecurityQuestionSetupView,
    SecurityQuestionVerifyView,
    TextCaptchaVerifyView,
    TOTPSetupMFAView,
    TOTPSetupView,
    TOTPVerifyView,
    VoiceSetupView,
    VoiceVerifyView,
    admin_dashboard,
    admin_logs,
    about,
    dashboard,
    home,
    how_it_works,
    profile,
    user_dashboard,
    document_list,
    serve_document,
    delete_document,
)

app_name = "accounts"

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("how-it-works/", how_it_works, name="how-it-works"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("password-reset/", PasswordResetRequestView.as_view(), name="password-reset"),
    path("password-reset/verify-otp/", PasswordResetOTPVerifyView.as_view(), name="password-reset-verify-otp"),
    path("password-reset/confirm/", PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("choose-factor/", CurrentFactorRouterView.as_view(), name="choose-factor"),
    path("verify-otp/", OTPVerifyView.as_view(), name="verify-otp"),
    path("verify-captcha/", CaptchaVerifyView.as_view(), name="verify-captcha"),
    path("verify-image/", ImageVerifyView.as_view(), name="verify-image"),
    path("verify-text-captcha/", TextCaptchaVerifyView.as_view(), name="verify-text-captcha"),
    path("verify-totp/", TOTPVerifyView.as_view(), name="verify-totp"),
    path("verify-pin-setup/", PinSetupView.as_view(), name="verify-pin-setup"),
    path("verify-pin/", PinVerifyView.as_view(), name="verify-pin"),
    path("verify-question-setup/", SecurityQuestionSetupView.as_view(), name="verify-question-setup"),
    path("verify-question/", SecurityQuestionVerifyView.as_view(), name="verify-question"),
    path("verify-voice-setup/", VoiceSetupView.as_view(), name="verify-voice-setup"),
    path("verify-voice/", VoiceVerifyView.as_view(), name="verify-voice"),
    path("verify-passkey/", PasskeyVerifyView.as_view(), name="verify-passkey"),
    path("verify-passkey-setup/", PasskeySetupMFAView.as_view(), name="verify-passkey-setup"),
    path("setup-totp/", TOTPSetupView.as_view(), name="setup-totp"),
    path("verify-totp-setup/", TOTPSetupMFAView.as_view(), name="verify-totp-setup"),
    path("resend-otp/", OTPResendView.as_view(), name="resend-otp"),
    path("passkeys/register/options/", PasskeyRegistrationOptionsView.as_view(), name="passkey-register-options"),
    path("passkeys/register/verify/", PasskeyRegistrationVerifyView.as_view(), name="passkey-register-verify"),
    path("passkeys/auth/options/", PasskeyAuthenticationOptionsView.as_view(), name="passkey-auth-options"),
    path("passkeys/auth/verify/", PasskeyAuthenticationVerifyView.as_view(), name="passkey-auth-verify"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/admin/", admin_dashboard, name="admin-dashboard"),
    path("dashboard/user/", user_dashboard, name="user-dashboard"),
    path("profile/", profile, name="profile"),
    path("dashboard/admin/logs/", admin_logs, name="admin-logs"),
    path("documents/", document_list, name="document-dashboard"),
    path("documents/view/<int:document_id>/", serve_document, name="document-view"),
    path("documents/delete/<int:document_id>/", delete_document, name="document-delete"),
    path("logout/", AppLogoutView.as_view(), name="logout"),
]
