from django.urls import path

from .views import (
    AppLogoutView,
    CaptchaVerifyView,
    CurrentFactorRouterView,
    ImageVerifyView,
    LoginView,
    OTPResendView,
    OTPVerifyView,
    PasskeyAuthenticationOptionsView,
    PasskeyAuthenticationVerifyView,
    PasskeyRegistrationOptionsView,
    PasskeyRegistrationVerifyView,
    PasskeyVerifyView,
    PinVerifyView,
    RegisterView,
    SecurityQuestionVerifyView,
    TOTPSetupView,
    TOTPVerifyView,
    admin_dashboard,
    about,
    dashboard,
    home,
    how_it_works,
    user_dashboard,
)

app_name = "accounts"

urlpatterns = [
    path("", home, name="home"),
    path("about/", about, name="about"),
    path("how-it-works/", how_it_works, name="how-it-works"),
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("choose-factor/", CurrentFactorRouterView.as_view(), name="choose-factor"),
    path("verify-otp/", OTPVerifyView.as_view(), name="verify-otp"),
    path("verify-captcha/", CaptchaVerifyView.as_view(), name="verify-captcha"),
    path("verify-image/", ImageVerifyView.as_view(), name="verify-image"),
    path("verify-totp/", TOTPVerifyView.as_view(), name="verify-totp"),
    path("verify-pin/", PinVerifyView.as_view(), name="verify-pin"),
    path("verify-question/", SecurityQuestionVerifyView.as_view(), name="verify-question"),
    path("verify-passkey/", PasskeyVerifyView.as_view(), name="verify-passkey"),
    path("setup-totp/", TOTPSetupView.as_view(), name="setup-totp"),
    path("resend-otp/", OTPResendView.as_view(), name="resend-otp"),
    path("passkeys/register/options/", PasskeyRegistrationOptionsView.as_view(), name="passkey-register-options"),
    path("passkeys/register/verify/", PasskeyRegistrationVerifyView.as_view(), name="passkey-register-verify"),
    path("passkeys/auth/options/", PasskeyAuthenticationOptionsView.as_view(), name="passkey-auth-options"),
    path("passkeys/auth/verify/", PasskeyAuthenticationVerifyView.as_view(), name="passkey-auth-verify"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/admin/", admin_dashboard, name="admin-dashboard"),
    path("dashboard/user/", user_dashboard, name="user-dashboard"),
    path("logout/", AppLogoutView.as_view(), name="logout"),
]
