# Generated by Django 6.0.3 on 2026-04-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginactivity",
            name="device_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="loginactivity",
            name="is_trusted_device",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loginactivity",
            name="is_unusual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loginactivity",
            name="location_label",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
