# Generated by Django 6.0.3 on 2026-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_loginactivity_device_name_loginactivity_is_trusted_device_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='loginactivity',
            name='auditlog_lo_email_c6e97e_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginactivity',
            name='auditlog_lo_status_cba931_idx',
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_PASSWORD', 'Failed Password'), ('FAILED_OTP', 'Failed OTP'), ('LOCKED', 'Locked'), ('OTP_SENT', 'OTP Sent')], max_length=20),
        ),
    ]
