# Generated by Django 6.0.3 on 2026-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='factor',
            field=models.CharField(choices=[('EMAIL', 'Email OTP'), ('PHONE', 'Phone OTP')], default='EMAIL', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, choices=[('PET', 'What was the name of your first pet?'), ('SCHOOL', 'What is the name of your primary school?'), ('CITY', 'In which city were you born?'), ('HERO', 'Who is your childhood hero?')], max_length=20),
        ),
    ]
