# Generated by Django 6.0.3 on 2026-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_failed_login_count_user_locked_until_trusteddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_phrase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_signature',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
