# Generated by Django 6.0.3 on 2026-04-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_voice_enabled_user_voice_phrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voice_profile_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='voice_reference_audio_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
