# Generated by Django 6.0.3 on 2026-05-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_document'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='accounts_do_user_id_a2e13b_idx',
        ),
    ]
